### ISSUE TITLE
Location hardware hardcoded in aar

### ISSUE THREAD

**Issue by AlessandroLacroce** [Appboy/appboy-unity-sdk#21]
We've seen that the following using-permission have been forced inside the appboy-unity.aar. Is it possible to leave the choice of inserting them to the developer? 

*ACCESS_FINE_LOCATION
ACCESS_COARSE_LOCATION*

Especially because they add the following restriction to the end-user: 

*android.hardware.LOCATION
android.hardware.location.GPS*

Thanks

**Comment by briancaw** [comment]
Hi @AlessandroLacroce 

We'll be updating this in our next Unity release so that no permissions are added by default.  That release should come out mid-next week at the latest.

Thanks,
Brian

**Comment by briancaw** [comment]
Hi again @AlessandroLacroce,

This is fixed now.  Please let us know if you have any other comments/questions regarding this functionality going forward.

Thanks again,
Brian
