### ISSUE TITLE
Build error using Unity and Windows 10.

### ISSUE THREAD

**Issue by TicTocGarth** [Appboy/appboy-unity-sdk#22]
Hello,

I am currently attempting to implement Appboy in a Unity 5.2.4f1 project for Windows 10. I get stuck when trying to build the project in Visual Studio 2015. I am using the Appboy v1.6.0 sdk. This is the output when building in VS.

```
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: Assembly-CSharp-firstpass, Configuration: Debug ARM ------
1>  Assembly-CSharp-firstpass -> C:\Users\TicTocGarth\Projects\LetsTestThis\AppboyTest\UWP\Assembly-CSharp-firstpass\bin\ARM\Debug\Assembly-CSharp-firstpass.dll
2>------ Build started: Project: AppboyTest, Configuration: Debug ARM ------
2>  UnityInstallationDir "C:\Program Files\Unity 5.2.4f1\Editor".
2>  UnityWSAPlayerDir "C:\Program Files\Unity 5.2.4f1\Editor\Data\PlaybackEngines\metrosupport".
2>  UnityProjectDir "C:\Users\TicTocGarth\Projects\LetsTestThis\AppboyTest".
2>  Copying unprocessed assemblies...
2>C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.2\Microsoft.Windows.UI.Xaml.Common.targets(263,5): Xaml Internal Error error WMC9999: Index not found. (Exception from HRESULT: 0x80131124)
========== Build: 1 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

I also receive many "reference rewrite" errors in Unity when creating the VS solution. I can remove these errors if I check the "Do Not Process" flag in Unity's import settings.

```
Reference rewriter: Error: method `System.Reflection.MethodInfo System.Type::GetMethod(System.String,System.Reflection.BindingFlags)` doesn't exist in target framework. It is referenced from Lex.Db.dll at System.Reflection.MethodInfo Lex.Db.TypeHelper::GetStaticMethod(System.Type,System.String).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:558)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:118)
UnityEditor.HostView:OnGUI()
```

This is on a blank Windows 10 Unity project with only the Appboy plugins added. I have a sample project and a video of the build process if those would help!

**Comment by briancaw** [comment]
Hi @TicTocGarth 

We never officially updated our Windows Unity plugin for Windows 10, so it's possible/likely that there some snags there as the update from 8.1 to 10 required some of our dependencies to update that live un-updated in this plugin (our library required no changes though).  

If you can try the following it would be greatly appreciated; however, I will follow this path ASAP (i.e. tomorrow), so no worries if not:

Generate a new Windows Universal project, install the Appboy Universal nuget package, update dependencies (notably Lex.db) and confirm it builds.  If so, copy the DLLs in the output directory to your plugin folder and retry building Unity.  In short, try updating the dependencies (namely Lex.db) in the plugin.

I'll report more tomorrow as I dive in further.  Thanks very much for your thorough reporting of the issue; hoping to have this resolved quickly.

- Brian

**Comment by briancaw** [comment]
Hi Again @TicTocGarth,

Can you let me know what SDK you're building against in the Unity build settings (i.e. 8.0, 8.1, phone8.1, universal 8.1, or universal 10).

Thanks,
Brian

**Comment by briancaw** [comment]
Hey @TicTocGarth 

I've created a branch here with instructions for how to get things working on Windows 10.  I had to update our Lex.db dependency to one that supports Windows 10, and I also had to refactor the plugin and update some settings because since our last update Unity has made breaking changes to how Windows plugins are handled.  There are a couple more integration steps, but we'll look into solutions for making those automatic in the future.

Please let me know if you have any comments/questions/issues with updated solution.  We'll update with information regarding an official release for Windows 10 Unity as we strategize around that and come up with concrete plans.

Thanks very much,
Brian

**Comment by briancaw** [comment]
Also, you can find the branch/directory here:  https://github.com/Appboy/appboy-unity-sdk/tree/feature/w10/w10plugin

**Comment by TicTocGarth** [comment]
I am building using Universal 10. I'll try making the blank project then nuget'ing the packages from VS.

I can build by waiting to nuget add Appboy until after the VS project is loaded. So I can avoid loading the DLL into Unity and only load it in VS. I can use this as a workaround to implement Appboy in our product.

I am busy tomorrow, but I'll check out the branch on Saturday. Thank you!

**Comment by briancaw** [comment]
Hey @TicTocGarth 

Were you able to get things working with the new branch?

Thanks,
Brian

**Comment by TicTocGarth** [comment]
Currently I am able to get reporting working for x64, but when I build from Visual Studio to this Nokia Lumia 929 Win 10 Phone, I receive an UnhandledException when we run the app.
```
Message	"System.DllNotFoundException: Unable to load DLL 'Kernel32.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)\r\n   at Lex.Db.WinApi.GetFileAttributesEx(String name, Int32 fileInfoLevel, FILE_ATTRIBUTE_DATA& lpFileInformation)\r\n   at Lex.Db.WinApi.GetFileAttributes(String path)\r\n   at Lex.Db.OSDirectory.Exists(String path)\r\n   at Lex.Db.FileSystem.DbSchemaStorage.Open()\r\n   at Lex.Db.DbInstance.Initialize()\r\n   at A.c90d33938adad80f42c102d47adff8e4b.cde1fadf5fda777e1eb83c999d62"	string
```
Removing this DLL and using Lex.db from nuget let the app run on Windows 10 Phone, however then reporting does not seem to work for any cpu architecture.

**Comment by briancaw** [comment]
Hi @TicTocGarth 

Thanks for the update - I'll continue to look into this.  For the Windows 10 case - can you ensure that you have all of the other dependencies there?  i.e. We've seen it happen occasionally where if Newtonsoft.JSON or NodaTime are missing things just stop working silently.

Thanks,
Brian

**Comment by TicTocGarth** [comment]
So I've done some more testing, and it seems like this is not just a Unity thing.

1. Create a new "Windows Universal" blank app in Visual Studio 2015.
2. Use nuget to add "AppboyPlatform.Universal.Release". This should also install Newtonsoft.JSON and NodaTime.
3. I added these lines of code to App.xaml.cs
```
using AppboyPlatform.PCL.Managers;
using AppboyPlatform.Universal;
using AppboyPlatform.Universal.Managers.PushArgs;
```
Then in the OnLaunched method
```
Appboy.SharedInstance.OpenSession();
Appboy.SharedInstance.ChangeUser("exampleuser");
Appboy.SharedInstance.AppboyUser.Email = "garthosmith@gmail.com";
```
And in OnSuspended `Appboy.SharedInstance.CloseSession();`

This runs fine on my Win 10 desktop in both x86 and x64 builds.
However, it crashes on my Win 10 Phone (Lumia 929). This exception gets thrown. `Exception thrown: 'System.DllNotFoundException' in Lex.Db.dll`

Adding NodaTime via nuget tells me I'm updating from NodaTime 1.3.0 to NodaTime 1.3.2. Adding Newtonsoft.JSON via nuget tells me I'm updating from Newtonsoft.Json.6.0.5 to Newtonsoft.Json.8.0.3. However, I still receive exception, `Exception thrown: 'System.DllNotFoundException' in Lex.Db.dll`

**Comment by briancaw** [comment]
Hi @TicTocGarth 

Apologies that we let this issue get so stale.  Everything should work probably if you update your Lex.db dependency to be 1.2.5 (note 1.2.6 has a bug, so it must be exactly 1.2.5).

Also note that we'll be updating our Windows support holistically in the upcoming months so that future iterations should have less snags.  Please let me know if updating Lex.db to 1.2.5 doesn't solve things for you, and I'll be sure to update on our next Windows release which should point to the right dependencies by default.

Thanks,
Brian
