### ISSUE TITLE
1.10.0: "Updates the Android plugin to use Appboy Android SDK 1.18.0."

### ISSUE THREAD

**Issue by Will5** [Appboy/appboy-unity-sdk#24]
The changelog says that `1.10.0` `Updates the Android plugin to use Appboy Android SDK 1.18.0.`. When importing the project however, I see that the Appboy Android SDK is 1.15.0, not 1.18.0.

**Comment by Wenzhi** [comment]
Hey @Will5,

Thanks for reporting the issue! We checked and confirm that the Appboy Android SDK is 1.15.0. We will have a release coming next week, and it should fix this issue. If you need the fix earlier than next week, please let us know!

Thanks,
Wenzhi

**Comment by Will5** [comment]
Hey @Wenzhi,

I look forward to the release coming next week.

Thanks,
Will5

**Comment by Wenzhi** [comment]
Hey @Will5,

We just released the Unity SDK 1.11.0 with the latest Appboy Android and iOS SDK. Please check it and let us know if it solves your issue.

Thanks,
Wenzhi

**Comment by Wenzhi** [comment]
Hey @Will5 ,

Due to lack of response, we will close this issue assuming it's fixed. Please feel free to re-open it if you are still seeing the issue in the latest version.

Thanks,
Wenzhi
