### ISSUE TITLE
IAppboyUnityInAppMessageListener != IInAppMessageManagerListener

### ISSUE THREAD

**Issue by Will5** [Appboy/appboy-unity-sdk#25]
This is a feature request. Even though the Appboy Unity SDK for Android is fairly up to date with the Appboy SDK for Android, the Unity SDK does not have feature parity with the Android SDK. Specifically, we would like to have more control over the lifecycle of an in-app message.

The Appboy SDK for Android's IInAppMessageManagerListener has methods for
- onInAppMessageReceived
- beforeInAppMessageDisplayed
- onInAppMessageClicked
- onInAppMessageButtonClicked
- onInAppMessageDismissed

The Appboy Unity SDK for Android's IAppboyUnityInAppMessageListener has methods for
- onInAppMessageReceived
- onInAppMessageClicked
- onInAppMessageButtonClicked

**Comment by Wenzhi** [comment]
Hey @Will5,

Thanks for the report! We put this request and the other request you made [here](https://github.com/Appboy/appboy-unity-sdk/issues/26) on our roadmap. However, as the features require an Android SDK release and then a Unity release, we don't have a timeline for these requests yet. 

To help us understand the request better, could you let us know:
- When do you need the features? Do you have a deadline for it?
- Which version of Unity are you using?
- What are your use cases for `beforeInAppMessageDisplayed` and `onInAppMessageDismissed`?
- For `beforeInAppMessageDisplayed`, which display options would be useful for you (e.g. display now, discard, display later, etc.)

Thanks,
Wenzhi

**Comment by Will5** [comment]
Hi @Wenzhi,

- We got around this for now by adding more events as triggers, but ideally the sooner the better. Since we will soon have to update anyway for the TLS 1.0/1.1 Deprecation, that might be a good timeframe for us.

- We are currently using Unity 5.6.2f1.

- On Native, we were using beforeInAppMessageDisplayed to control under what screens / views or conditions an In-App Message is allowed to display. Currently, on Unity, if we don't specify an event trigger, the IAM shows up over the splash screen, which also seems to halt the Unity Engine.

- We have only used Display Now and Display Later.

Thanks,
Will

**Comment by Bucimis** [comment]
Hi @Will5,

We have implemented an extended IAppboyUnityInAppMessageListener in the following `aar`. Would it be possible for you to replace the `appboy-unity.aar` aar in your `Assets/Plugins/Android/libs/` folder with the following `aar`?

https://drive.google.com/file/d/0B8NXmED5JgZDMmJKVmFPTVUzenM/view?usp=sharing

Note that our Unity code is available here https://github.com/Appboy/appboy-android-sdk/tree/master/android-sdk-unity, if you ever need to make further modifications or build from scratch.

We will include this update in our next release of Unity, but note that that next release will be for Unity 2017.

Thanks,
Jared

**Comment by Will5** [comment]
Thanks, is this in 1.12.0?

**Comment by Bucimis** [comment]
@Will5 thanks for following up. Yep, we've fully fleshed out our Unity IAM listener - see https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-unity/src/com/appboy/unity/IAppboyUnityInAppMessageListener.java for the new interface
