### ISSUE TITLE
Using deep links with Unity SDK

### ISSUE THREAD

**Issue by wbelfieldkix** [Appboy/appboy-unity-sdk#29]
I'm having issues getting push notification callbacks to fire and deep links from Appboy push notifications working with my Android Unity App and just wanted to verify what is needed for this.

My app is integrated with the unity appboy sdk and can receive push notifications, but neither the 'PushNotificationReceivedCallback' nor 'PushNotificationOpenedCallback' fire when the notification is received.  I have an 'AppboyListener' game object in the main scene with the included 'AppboyListener.cs' as a component (standard setup based on the integration docs.)  Clicking the notification DOES open the app as expected, just none of the callbacks fire.

As for deep links, is setting 'com_appboy_handle_push_deep_links_automatically' to 'true' in appboy.xml sufficient to handle deep links from a push notification?  Currently if I set the 'on click' behavior of a push notification to deep link into the app (with url 'bpcompanion://battlelog') it will cause my app to crash.  There is mention of updating a BroadcastReceiver to support deep links, but I wasn't sure how this should be added to work with the unity sdk.

Any help is much appreciated, thanks!

**Comment by Bucimis** [comment]
Hi @wbelfieldkix,

Thanks for getting in touch!

1) re push callbacks - Push callbacks are not supported at this time on Android+Unity and any reference to them in sample code is incorrect. We will remove the incorrect references in a future release and apologize for the confusion. Note that we could potentially add the feature as a feature going forward - please let us know what usecases you are envisioning and their relative importance.

2) re deep links - Yes, setting 'com_appboy_handle_push_deep_links_automatically' to 'true' in your appboy.xml should be all the setup needed to handle opening deep links and websites from push.  To define your own custom deep links, please follow the section entitled "Creating Custom Deep Links" in our Android deep linking documentation available here: https://www.braze.com/documentation/Android/#step-3-add-deep-links.  To debug why a given deep link is not working, check out our deep link troubleshooting guide: https://www.braze.com/documentation/Android/#deep-links-not-working (in particular, I recommend the first step - that `adb` command replicates the system command the Braze SDK will make to open custom deep links).  Unity+Android deep links are substantially just Android deep links, so all Android-specific documentation should apply.

Thanks again,
Braze SDK Engineering
