### ISSUE TITLE
ANDROID ONLY - HTML IAM not returning focus to app on dismissal

### ISSUE THREAD

**Issue by JFinKix** [Appboy/appboy-unity-sdk#31]
Hi,

I've contacted one of your developers directly by email regarding this issue and was pointed towards this ticket submission process.

We recently integrated the latest version of your SDK into our product, and have encountered an issue where HTML IAMs do not return focus to our application when they are dismissed via a CLOSE button. This issue has not happened on our iOS client. 

The issue manifests itself as the application appearing frozen with the Android task bar & navigation buttons visible. Selecting any of the navigation buttons will resolve the issue.

As a result of this, we have had to roll back the updated SDK on our Android client, as the current user experience is sub optimal. 

If you need any additional information please let me know, I can get Android Device logs from our QA team, and screenshots etc. if required. 

Regards,
James (KIXEYE - Gameplay Engineer)

**Comment by Bucimis** [comment]
Hi @JFinKix,

Thanks for filing. We've repro'd your issue and have a fix waiting in the wings. We will update you with progress and timing details as they come.

Would you potentially be interested in receiving beta builds containing any fixes for testing purposes?

Thanks,
Jared

**Comment by JFinKix** [comment]
Hi Jared,

Thanks for looking into that so quickly. At this point in time our team have rolled back the SDK update and released a new version of our Android APK with the previous version of the Braze SDK.

For the moment we will not be investing time in instrumenting beta fixes into our project, but once the fix is confirmed we can reassess and find time in our development schedule to upgrade the SDK again.

Regards,
James (KIXEYE - Gameplay Engineer)

**Comment by Bucimis** [comment]
@JFinKix thanks, appreciate the update. We'll let you know when the fix is live

**Comment by Bucimis** [comment]
Hi @JFinKix,

We just released Unity SDK 1.13.0, which updates our Android SDK to a version that contains the following fix: https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#225 (see "Changed")

Please let us know if you continue to experience this issue.

Thanks!
Braze SDK Engineering
