### ISSUE TITLE
Push notifications with Android Oreo

### ISSUE THREAD

**Issue by wbelfieldkix** [Appboy/appboy-unity-sdk#33]
Our app uses the Braze SDK to handle push notifications, and this works fine except for devices using Android 8.  

I've been testing this out with a campaign configured in the braze dashboard to use the fallback channel.  User 5072195 is on Android 6.0 and gets the notifications while user 5072250 on Android 8.0 doesn't.  Both users show up as 'Opted In' under Engagement/Contact Settings.  The android 8 user doesn't have any campaigns/push received, while the android 6 user does.

According to the documentation it seems that notifications can use the 'default'/'fallback' channel to get sent to android 8 devices without any code or config changes.  Are there any sdk configuration requirements to allow push notifications on android 8?  We're on version 1.11 of the braze unity sdk.

**Comment by wbelfieldkix** [comment]
Fixed this issue by switching to an older android sdk.  We aren't using features of the latest anyway so this solution works for us.

**Comment by radixdev** [comment]
Hello @wbelfieldkix ,

Unity SDK 1.12 adds Android O support. Please let us know if this fixes your issue.

Thanks,
Braze Team

**Comment by wbelfieldkix** [comment]
We've updated to the 1.15 Unity SDK and Android 9 (API level 28) and are still seeing this issue.  The AndroidManifest has been updated to use AppboyFcmReceiver and the REGISTRATION intent removed.  Do we need to explicitly create a new channel to get push notifications to work on Android 8+ devices?

**Comment by radixdev** [comment]
@wbelfieldkix can you share [complete verbose logs](https://www.braze.com/documentation/Android/#verbose-logging) from your device when you fail to display the push? This will help us track down why push isn't showing in your integration. There is no need to create a new channel for Android O+ devices, we use a fallback channel when no channel is present.

Additionally, what version of the support library are you using and what is your target SDK version?

**Comment by wbelfieldkix** [comment]
Target android sdk is 28.  I just did the full braze unity sdk import.  Does that have the necessary support libs included or so those need to be downloaded separately?  We're also using the facebook sdk so have some v25 libs around for that, but I didn't get any conflicts when building so figured there wasn't overlap with braze sdk dependencies.

**Comment by pagrawal1407** [comment]
@radixdev I am using 'com.appboy:android-sdk-ui:2.0.5' Braze SDK in my android app. When my app was targeting android sdk 25, I was receiving push notifications on devices with API 25 and below as well as API 26 (Android O) and above. But when I change the targetsdkversion on my app to 27, I stooped receiving push notifications on devices running API 26 (Android O) and above. I still receive the notifications for older Android version devices. I am using default notification channel in my Braze campaigns. Can you help me figure out why its happening?

**Comment by radixdev** [comment]
@pagrawal1407 See https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#210 . Notification Channel support was added in 2.1.0.
