### ISSUE TITLE
iOS - Issue with SDWebImage and FLAnimatedImage when building with CI

### ISSUE THREAD

**Issue by nlattessi** [Appboy/appboy-unity-sdk#34]
Hi.

In our pipeline we build our Unity projects through CI (Continuos Integration). In this scenario, we encounter an issue when testing our product on runtime regarding issues finding libraries SDWebImage and FLAnimatedImage.

We can resolve it doing a manual build and configuring in Xcode both libraries as embedded binaries but this manual process don't fix this issue when building with CI.

We found a solution using method `AddFileToEmbedFrameworks` from `UnityEditor.iOS.Xcode.Extensions`. I'm pushing a PR with an updated PostBuild.cs adding this process.

PR: https://github.com/Appboy/appboy-unity-sdk/pull/35

**Comment by Sencerd** [comment]
I have encountered this issue as well, and your PR fixes it for me. Thank you!

**Comment by nlattessi** [comment]
A quick note: method `AddFileToEmbedFrameworks` is available in Unity as of **2017.2** version.

In one of our projects we used to have 5.6.x and this fix didn't apply. We tried building manually Xcode Manipulation module (https://bitbucket.org/Unity-Technologies/xcodeapi) and adding it as dll but this workaround didn't help for us because resulting dll throwed conflicts with other modules (specifically Firebase modules)

Hope it helps!

**Comment by Bucimis** [comment]
Thanks everyone! esp @nlattessi for the fix - you'll get a shoutout in our next changelog :)

**Comment by vietphan90vn** [comment]
Hi @nlattessi with this fix, you are breaking the compatible with Unity 5x, I already make an iOS Xcode custom extension from (https://bitbucket.org/Unity-Technologies/xcodeapi) and it's work for me. I'll make a pull request later to help any project using Unity 5 (like as my project)
