### ISSUE TITLE
Rich notifications on iOS

### ISSUE THREAD

**Issue by wbelfieldkix** [Appboy/appboy-unity-sdk#39]
Rich notifications aren't working for us on iOS, only the standard notification message displays.  The same campaign displays correctly as a rich notification on Android, however.

Does iOS require additional config to allow rich notifications to display?  We're on v1.11 of the Unity SDK.

**Comment by Bucimis** [comment]
@wbelfieldkix thanks for getting in touch! For for rich notifications on iOS, additional integration steps in Xcode are required. Please see https://www.braze.com/documentation/iOS/#creating-a-service-extension

**Comment by wbelfieldkix** [comment]
Thanks, figured that might be necessary, but wanted to verify that it was required with the Unity plugin.
