### ISSUE TITLE
Unsupported Architectures x86_64, i286 when submitting for Distribution on iOS

### ISSUE THREAD

**Issue by Kseniya** [Appboy/appboy-unity-sdk#40]
After updating appboy unity sdk from 1.9.0 to 1.13.0 we are getting this errors when submitting an iOS build to the app store:
![image 3](https://user-images.githubusercontent.com/665299/42659008-ea94c18c-85f4-11e8-8947-97d93872b0f3.png)

It sounds like the problem is that SDWebImage and FLAnimatedImage frameworks are archived with support for simulator architectures.

We tried stripping out those architectures manually using `lipo -remove i386 ProjectFramework_SDK -o ProjectFramework_SDK` and `lipo -remove x86_64 ProjectFramework_SDK -o ProjectFramework_SDK` and after that build gets submitted to the app store with no problems.

Have anyone else seen this issue? Is this the correct solution? If that's the case, can it be incorporated into the SDK itself?

**Comment by Bucimis** [comment]
@Kseniya thanks for reaching out. We're working on a fix and can confirm that for right now, `lipo`ing the existing Frameworks is the recommended workaround.

**Comment by Bucimis** [comment]
@Kseniya this fixed in 1.14.0 https://github.com/Appboy/appboy-unity-sdk/releases/tag/1.14.0 - please reopen if you continue to experience the issue
