### ISSUE TITLE
Android HTML push notification showing raw text

### ISSUE THREAD

**Issue by iliaga** [Appboy/appboy-unity-sdk#44]
I've enabled html notifications in appboy.xml and im using the latest unity sdk.

then, sent an html tagged text in the title and body of the notification.

are anymore steps required?

**Comment by Bucimis** [comment]
Hi @iliaga, HTML notifications were added in Android SDK version 3.1.1 (https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#311) but the Unity SDK currently ships with the earlier 3.1.0 (https://github.com/Appboy/appboy-unity-sdk/blob/master/CHANGELOG.md#1160). HTML notifications will become available after the next Unity release.

Potential workaround - if you're building the Braze Unity SDK from source and referencing our `aar` artifacts from within your `Plugins` directory, you may update those to 3.1.1 directly (`aar` files are available at https://github.com/Appboy/appboy-android-sdk/tree/gh-pages/sdk/com/appboy/android-sdk-base/3.1.1 https://github.com/Appboy/appboy-android-sdk/tree/gh-pages/sdk/com/appboy/android-sdk-ui/3.1.1).

**Comment by iliaga** [comment]
renamed and replaced, but still didn't work.
my priorities changed for now so i will not try to use the workaround and wait for the update.
thanks ! :)

**Comment by iliaga** [comment]
any idea on when will this be integrated?

**Comment by Bucimis** [comment]
Hi @iliaga, we've just released 1.17.0, which uses the latest android sdk (3.2.0) and supports HTML push. Thanks!
