### ISSUE TITLE
Android HTML Notifications Still Dont work sdk version 1.17.0v

### ISSUE THREAD

**Issue by iliaga** [Appboy/appboy-unity-sdk#46]
I am trying to use HTML notifications now with the new sdk.
Am I doing something wrong ? 

![image](https://user-images.githubusercontent.com/46316027/55290088-1a8c7f00-53d7-11e9-8165-8ca70016c3a8.png)

this messege still shows raw text instead of stylized text.

**Comment by Bucimis** [comment]
Hi @iliaga, did you set the boolean field `com_appboy_push_notification_html_rendering_enabled` to `true` in your `appboy.xml`? For more info, see https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#added-2

**Comment by iliaga** [comment]
yes it does sorry my bad.
