### ISSUE TITLE
Push notifications arrive, but don't open app

### ISSUE THREAD

**Issue by TagGamesJames** [Appboy/appboy-unity-sdk#48]
While upgrading our project we encountered a problem with push notifications on android devices. We're currently unsure if this is due to Braze's handling, or Firebase's since no error logs appear to point us to an exact reasoning. 

From the Braze dashboard we are able to send a notification to our devices using the `Open App` on click behaviour. These notifications arrive successfully to our device, but on clicking them we receive a log specifying:

`com.appboy.AppboyFcmReceiver: Received broadcast message. Message: Intent { act=com.appboy.action.APPBOY_PUSH_CLICKED flg=0x10 cmp=*ourPackageName*/com.appboy.AppboyFcmReceiver (has extras) }`

`06-06 16:43:19.196 32005-32074/? I/Appboy v3.2.1 .com.appboy.Appboy: No campaign Id associated with this notification. Not logging push click to Appboy.`

After this point the notification dismisses itself, and nothing happens after this point. Looking through all the troubleshooting pages, and past issues we haven't encountered anyone specifying a problem with the notifications failing to launch the app. Is there anyway to amend this or discover why the notification isn't resulting in the app opening?

Additional details: 
In our AndroidManifest we're using the prime31compatible AppboyUnityPlayerNativeActivity, and have a structure following:

```xml
    <activity android:name="com.appboy.unity.prime31compatible.AppboyUnityPlayerNativeActivity" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:screenOrientation="sensor">

      <meta-data android:name="android.app.lib_name" android:value="unity" />
      <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />      
      <meta-data android:name="unityplayer.UnityActivity" android:value="true"/>
      
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <category android:name="android.intent.category.LEANBACK_LAUNCHER" />
      </intent-filter>

      <!-- Required for schemeName://store deeplink -->
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="schemeName" android:host="Braze"/>
      </intent-filter>

    </activity>

    <!-- ============= Braze ============= -->

    <activity android:name="com.appboy.unity.AppboyOverlayActivity" android:theme="@style/Appboy.Theme.Transparent" />
      <activity android:name="com.appboy.ui.AppboyWebViewActivity" android:theme="@android:style/Theme" /> 
      <activity android:name="com.appboy.ui.activities.AppboyFeedActivity" android:theme="@android:style/Theme" />

    <service android:name="com.appboy.AppboyFirebaseMessagingService">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>
```

The permissions we use are:
```xml
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.GET_ACCOUNTS" android:maxSdkVersion="18" />
  <uses-permission android:name="android.permission.WAKE_LOCK" />

  <permission
      android:name="com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS"
      android:protectionLevel="signature"
        />
  <uses-permission android:name="com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS" />
```
These obviously aren't all intended for Braze.

**Comment by radixdev** [comment]
Can you provide [verbose & unfiltered logs](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration/#braze-log-level) starting from before you open the app to sometime after you click the push? Additionally, can you provide a test APK that we can send push to?

You can also email support@braze.com if this information is sensitive.

**Comment by radixdev** [comment]
Could you also try adding `<bool name="com_appboy_handle_push_deep_links_automatically">true</bool>` to your `appboy.xml`?

**Comment by TagGamesJames** [comment]
We were worried altering that setting since we inherited this code base would have affected how deep links were currently handled within the game. That doesn't seem to be the case and fixes the issue. Thanks for your help resolving the issue
