### ISSUE TITLE
In version 1.19 FLAnimatedImage.framework addition was removed

### ISSUE THREAD

**Issue by MartinGonzalez** [Appboy/appboy-unity-sdk#49]
In a previous pull request https://github.com/Appboy/appboy-unity-sdk/releases/tag/1.13.0
This line in

AddFileToEmbedFrameworks(project, target, Application.dataPath + "/Plugins/iOS/FLAnimatedImage.framework", "Frameworks/Plugins/iOS/FLAnimatedImage.framework");

was added in Assets/Plugins/Appboy/Editor/PostBuild.cs but in 1.19 is no more and build is failing. Is there any reason why it was removed?

**Comment by Bucimis** [comment]
@MartinGonzalez Braze Unity SDK 1.19.0 depends on Braze iOS SDK 3.16.0. In Braze iOS SDK 3.15.0, the SDWebImage dependency was bumped from major version 4 to 5 and the FLAnimatedImage dependency was removed.

As a result, Unity-generated XCode projects (starting with Braze Unity SDK 1.19.0) only need to embed the Braze SDK and SDWebImage frameworks.

See https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#3150
