### ISSUE TITLE
Example link of GameObject PushNotification Listener is broken.

### ISSUE THREAD

**Issue by MartinGonzalez** [Appboy/appboy-unity-sdk#50]
I was reading the docs [here](https://www.braze.com/docs/developer_guide/platform_integration_guides/unity/ios/push_notifications/#step-3-setting-push-listeners) and found that the example of the gameObject script used to listen  push notifications is broken. (Also several links are broken)

Broken link: https://github.com/Appboy/unity-sdk/blob/develop/Assets/Plugins/Appboy/Tests/AppboyBindingTester.cs#L44

I would need to know the signature of the method.

**Comment by Bucimis** [comment]
Thanks for the report - just want to ack that we've seen this and are triaging

**Comment by radixdev** [comment]
Apologies for the late response. This documentation is being updated and I will close this issue once they're live.
