### ISSUE TITLE
Add Assembly Definitions to Appboy Plugin.

### ISSUE THREAD

**Issue by MartinGonzalez** [Appboy/appboy-unity-sdk#52]
This would be really useful for those who use Asmdef in their project. I can create a pull request if you are in favor of this idea.

**Comment by Bucimis** [comment]
@MartinGonzalez would people who don't use Asmdef be unaffected? Feel free to raise a pull request, we welcome open source contributions & incorporate them when appropriate.

**Comment by Bucimis** [comment]
@MartinGonzalez is this still an issue for you? We haven't heard other customers ask for this but wanted to check in.

**Comment by starikcetin** [comment]
@Bucimis Of course this is an issue! All UPM packages are required to have asmdef files, and when you don't put asmdef files in your code I can't consume them from my UPM pacakge and need to create asmdef files dynamically.

People who don't use asmdefs can still use your code without changing anything as long as you leave "Auto Referenced" enabled in your asmdef files:

> Specify whether the predefined assemblies should reference this Project assembly. When you disable the Auto Reference option, Unity does not automatically reference the assembly during compilation. This has no effect on whether Unity includes it in the build.

See here: https://docs.unity3d.com/Manual/class-AssemblyDefinitionImporter.html#general

**Comment by starikcetin** [comment]
Are there any updates yet? It has become very annoying to work with Braze because of this issue.

**Comment by radixdev** [comment]
Hi @starikcetin ,

We do not have any more updates. However we would be very open to any ideas (or PR) about how you'd like a Braze Unity asm definition(s) organized. Would there be a single `Asmdef` for each platform? What would be the most straightforward way to go about testing our `Asmdef` works in a project?

**Comment by starikcetin** [comment]
> Hi @starikcetin ,
> 
> We do not have any more updates. However we would be very open to any ideas (or PR) about how you'd like a Braze Unity asm definition(s) organized. Would there be a single `Asmdef` for each platform? What would be the most straightforward way to go about testing our `Asmdef` works in a project?

Hello @radixdev 

You don't need any platform-specificity. If it was working without asmdefs, it will work with asmdefs too. Asmdef files are only for C# source code, native plugins are not affected by asmdefs. You need 1 asmdef for runtime code, and another one for editor code, that's it.

**Comment by starikcetin** [comment]
@MartinGonzalez @Bucimis @radixdev
Created a PR that adds `asmdef` files: https://github.com/Appboy/appboy-unity-sdk/pull/94

**Comment by radixdev** [comment]
This has been released in version 3.8.1. Thank you @starikcetin and @MartinGonzalez for your patience!
