### ISSUE TITLE
iOS Deprecated API Usage Warning

### ISSUE THREAD

**Issue by Sencerd** [Appboy/appboy-unity-sdk#53]
We need a new version that updates to iOS SDK 3.19.0 to address this critical issue:

https://github.com/Appboy/appboy-ios-sdk/issues/198

**Comment by Bucimis** [comment]
@Sencerd we're on it, looking to release within 1-2 days

**Comment by Bucimis** [comment]
@Sencerd https://github.com/Appboy/appboy-unity-sdk/releases/tag/1.21.2 addresses this issue (all UIWebView usages are removed). Could you give it a shot and let us know how it goes?

**Comment by Sencerd** [comment]
Sorry for the late response, this is resolved, thanks!
