### ISSUE TITLE
3.20.1 TestFlight Upload Issues

### ISSUE THREAD

**Issue by KieranNeeMT** [Appboy/appboy-unity-sdk#54]
Hi Folks. I'm trying to update my app to 3.20.1 to fix the ITMS UIWebKit warning and for the iOS 13 push token collection issues. I'm running into a snag when trying to upload to TestFlight with XCode 10.2.1 however. There are a bunch of brand new ITMS errors (90087, 90209, 90125) coming from the upload script. The **only** thing changed in this branch was the new SDK so I'm hoping you can help.

The output looks like this:
`1 package(s) were not uploaded because they had problems:
	/var/folders/2x/4rydsdl17sxfz0mt36hbhyc00000gp/T/C1CA3646-924B-4599-B6C0-60216040335B/1298010172.itmsp - Error Messages:
		ERROR ITMS-90087: "Unsupported Architectures. The executable for MyApp..app/Frameworks/Appboy_iOS_SDK.framework contains unsupported architectures '[x86_64, i386]'."
		ERROR ITMS-90087: "Unsupported Architectures. The executable for MyApp..app/Frameworks/SDWebImage.framework contains unsupported architectures '[x86_64, i386]'."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'MyApp..app/Frameworks/Appboy_iOS_SDK.framework/Appboy_iOS_SDK' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'MyApp..app/Frameworks/SDWebImage.framework/SDWebImage' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
2019-09-16 17:35:43.500 altool[45111:3885293] *** Error: Errors uploading 'UnityMonctonClient/Builds/iOS/moncton/Moncton_TestFlight.ipa': (
    "Error Domain=ITunesTransporterErrorDomain Code=-18000 \"ERROR ITMS-90087: \"Unsupported Architectures. The executable for MyApp..app/Frameworks/Appboy_iOS_SDK.framework contains unsupported architectures '[x86_64, i386]'.\"\" UserInfo={NSLocalizedRecoverySuggestion=ERROR ITMS-90087: \"Unsupported Architectures. The executable for MyApp..app/Frameworks/Appboy_iOS_SDK.framework contains unsupported architectures '[x86_64, i386]'.\", NSLocalizedDescription=ERROR ITMS-90087: \"Unsupported Architectures. The executable for MyApp..app/Frameworks/Appboy_iOS_SDK.framework contains unsupported architectures '[x86_64, i386]'.\", NSLocalizedFailureReason=ERROR ITMS-90087: \"Unsupported Architectures. The executable for MyApp..app/Frameworks/Appboy_iOS_SDK.framework contains unsupported architectures '[x86_64, i386]'.\"}",
    "Error Domain=ITunesTransporterErrorDomain Code=-18000 \"ERROR ITMS-90087: \"Unsupported Architectures. The executable for MyApp..app/Frameworks/SDWebImage.framework contains unsupported architectures '[x86_64, i386]'.\"\" UserInfo={NSLocalizedRecoverySuggestion=ERROR ITMS-90087: \"Unsupported Architectures. The executable for MyApp..app/Frameworks/SDWebImage.framework contains unsupported architectures '[x86_64, i386]'.\", NSLocalizedDescription=ERROR ITMS-90087: \"Unsupported Architectures. The executable for MyApp..app/Frameworks/SDWebImage.framework contains unsupported architectures '[x86_64, i386]'.\", NSLocalizedFailureReason=ERROR ITMS-90087: \"Unsupported Architectures. The executable for MyApp..app/Frameworks/SDWebImage.framework contains unsupported architectures '[x86_64, i386]'.\"}",
    "Error Domain=ITunesTransporterErrorDomain Code=-18000 \"ERROR ITMS-90209: \"Invalid Segment Alignment. The app binary at 'MyApp..app/Frameworks/Appboy_iOS_SDK.framework/Appboy_iOS_SDK' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.\"\" UserInfo={NSLocalizedRecoverySuggestion=ERROR ITMS-90209: \"Invalid Segment Alignment. The app binary at 'MyApp..app/Frameworks/Appboy_iOS_SDK.framework/Appboy_iOS_SDK' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.\", NSLocalizedDescription=ERROR ITMS-90209: \"Invalid Segment Alignment. The app binary at 'MyApp..app/Frameworks/Appboy_iOS_SDK.framework/Appboy_iOS_SDK' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.\", NSLocalizedFailureReason=ERROR ITMS-90209: \"Invalid Segment Alignment. The app binary at 'MyApp..app/Frameworks/Appboy_iOS_SDK.framework/Appboy_iOS_SDK' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.\"}",
    "Error Domain=ITunesTransporterErrorDomain Code=-18000 \"ERROR ITMS-90209: \"Invalid Segment Alignment. The app binary at 'MyApp..app/Frameworks/SDWebImage.framework/SDWebImage' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.\"\" UserInfo={NSLocalizedRecoverySuggestion=ERROR ITMS-90209: \"Invalid Segment Alignment. The app binary at 'MyApp..app/Frameworks/SDWebImage.framework/SDWebImage' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.\", NSLocalizedDescription=ERROR ITMS-90209: \"Invalid Segment Alignment. The app binary at 'MyApp..app/Frameworks/SDWebImage.framework/SDWebImage' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.\", NSLocalizedFailureReason=ERROR ITMS-90209: \"Invalid Segment Alignment. The app binary at 'MyApp..app/Frameworks/SDWebImage.framework/SDWebImage' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.\"}",
    "Error Domain=ITunesTransporterErrorDomain Code=-18000 \"ERROR ITMS-90125: \"The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.\"\" UserInfo={NSLocalizedRecoverySuggestion=ERROR ITMS-90125: \"The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.\", NSLocalizedDescription=ERROR ITMS-90125: \"The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.\", NSLocalizedFailureReason=ERROR ITMS-90125: \"The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.\"}"`

I've checked using the lipo tool ([as outlined here](https://stackoverflow.com/a/49934320)) and the Frameworks do appear to contain more than just arm64.

Any ideas?

Thanks,
Kieran

**Comment by wclarkekixeye** [comment]
We have run into this same issue when trying to upload our release IPA to App Store Connect. This will likely prevent us from launching a new version prior to the release of iOS 13.

**Comment by rcousens** [comment]
Did someone build the Library dependencies for MacOS instead of iOS?

**Comment by Bucimis** [comment]
@KieranNeeMT @wclarkekixeye @rcousens which SDK versions are you building with? Could you try building with the Unity packages from our latest release - https://github.com/Appboy/appboy-unity-sdk/releases/tag/1.21.2?

**Comment by wclarkekixeye** [comment]
We are currently building with 1.21.1, as we don't make use of the HTML IAMs that were fixed in 1.21.2. I will try rebuilding the application with the updated SDK.

**Comment by KieranNeeMT** [comment]
We're also building with the 1.21.1 version. Worked round it by adding a shellscript to the XCode project that purges unsupported architectures in the build phases after the frameworks are embedded:
`echo "Target architectures: $ARCHS"

APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"
echo $(lipo -info "$FRAMEWORK_EXECUTABLE_PATH")

FRAMEWORK_TMP_PATH="$FRAMEWORK_EXECUTABLE_PATH-tmp"

# remove simulator's archs if location is not simulator's directory
case "${TARGET_BUILD_DIR}" in
*"iphonesimulator")
echo "No need to remove archs"
;;
*)
if $(lipo "$FRAMEWORK_EXECUTABLE_PATH" -verify_arch "i386") ; then
lipo -output "$FRAMEWORK_TMP_PATH" -remove "i386" "$FRAMEWORK_EXECUTABLE_PATH"
echo "i386 architecture removed"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_TMP_PATH" "$FRAMEWORK_EXECUTABLE_PATH"
fi
if $(lipo "$FRAMEWORK_EXECUTABLE_PATH" -verify_arch "x86_64") ; then
lipo -output "$FRAMEWORK_TMP_PATH" -remove "x86_64" "$FRAMEWORK_EXECUTABLE_PATH"
echo "x86_64 architecture removed"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_TMP_PATH" "$FRAMEWORK_EXECUTABLE_PATH"
fi
;;
esac

echo "Completed for executable $FRAMEWORK_EXECUTABLE_PATH"
echo $(lipo -info "$FRAMEWORK_EXECUTABLE_PATH")

done`

To use that script, I added the following to the PostBuild.cs script:
    ` var methodInfo = project.GetType().GetMethod(
					"AppendShellScriptBuildPhase",
					BindingFlags.NonPublic | BindingFlags.Instance,
					null,
					new Type[] { typeof(string), typeof(string), typeof(string), typeof(string) },
					null);
				if (methodInfo != null)
				{
					var defaultTarget = targets[0];
					const int AssetsFolderNameLength = 6; // "Assets"
					string projPath = Application.dataPath.Remove(Application.dataPath.Length - AssetsFolderNameLength);
					string scriptPath = projPath + "iOS_Resources/StripArchitectures.sh";
					methodInfo.Invoke(project, new object[] { defaultTarget, "AppBoyFrameworkStrip", "/bin/sh", scriptPath });
				}
				else
				{
					Debug.LogError("Unable to find method for AppendShellScriptBuildPhase. Have you updated past Unity 2018.2?");
				}
//****************`

The reflection is because the API isn't public pre Unity 2018.3 so that's the only way to get it (we're on 2018.2.f3 currently).

Also, I had to re-add the FLAnimated framework as it appeared to still be needed and the game wouldn't build without it.

**Comment by KieranNeeMT** [comment]
Going to close this as 1.21.2 appears to have resolved my issues. Thanks for the quick update & fix!
