### ISSUE TITLE
java.lang.NullPointerException: at com.appboy.ui.inappmessage.AppboyInAppMessageManager$2.onPageFinished

### ISSUE THREAD

**Issue by chanhpham9291** [Appboy/appboy-unity-sdk#56]
HeIlo,
 I got this exception on client logs:
`java.lang.NullPointerException:       at com.appboy.ui.inappmessage.AppboyInAppMessageManager$2.onPageFinished (Unknown Source:21)       at com.appboy.ui.inappmessage.InAppMessageWebViewClient.onPageFinished (Unknown Source:26)       at pn.b (PG:2)       at cC0.handleMessage (PG:64)       at android.os.Handler.dispatchMessage (Handler.java:112)       at android.os.Looper.loop (Looper.java:216)       at android.app.ActivityThread.main (ActivityThread.java:7625)       at java.lang.reflect.Method.invoke (Native Method)       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)       at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)`

This issue may be fixed in appboy-android-sdk v3.7.1:
https://github.com/Appboy/appboy-android-sdk/commit/c31da056fe41810861bd639bcb540c288709c0f4

Looks like the lastest appboy-unity-sdk is still using appboy-android-sdk v3.7.0.

Can I replace "Asset/Plugins/Android/libs/appboy-ui.aar" with "appboy-android-sdk v3.7.1" to fix this issue? Will it break anything in appboy-unity-sdk? 
:)

**Comment by radixdev** [comment]
Hi @chanhpham9291 ,

We're currently updating the unity sdk to be more up-to-date with the appboy-android-sdk SDK version used. In the meantime, you're absolutely correct in that you can replace that AAR with an updated one. You shouldn't have any problems/break anything. I will update this issue once that release is made.

**Comment by radixdev** [comment]
Hi @chanhpham9291 ,

The plugin has been updated to appboy-android-sdk version 5.0.0. Let us know if you have any more questions!
