### ISSUE TITLE
Update Version Number to Correct Release Number

### ISSUE THREAD

**Issue by kolibrigames-ajimine-vahid** [Appboy/appboy-unity-sdk#57]
https://github.com/Appboy/appboy-unity-sdk/blob/3008bb7922c153c6d301147aa2c4ed003e769085/Assets/Plugins/Appboy/AppboyBinding.cs#L21

This seems like this should be updated with the releases

**Comment by radixdev** [comment]
Hi @kolibrigames-ajimine-vahid ,

That field will be deprecated in a future release. Thank you for bringing this to our attention.

**Comment by radixdev** [comment]
Removed in the next release
