### ISSUE TITLE
Ability to track receiving remote notification

### ISSUE THREAD

**Issue by IgorGalimski** [Appboy/appboy-unity-sdk#59]
Hello! I'd like to know when my game was open by remote notification. How can I do it? Callbacks on gameobject work when the game is online, I need to track it offline.

**Comment by Bucimis** [comment]
Hi @IgorGalimski, are you looking for this functionality for iOS apps, Android apps, or both?

**Comment by IgorGalimski** [comment]
Hi! For android. I've tried this
`@Override
public void onCreate(Bundle savedInstanceState) {

    if (getIntent() != null) {
         Bundle dataBundle = getIntent().getExtras();
         // dataBundle contains the notification data payload
    }
}`

But it doesn't work

**Comment by Bucimis** [comment]
Hi @IgorGalimski, 

We recommend setting a Broadcast receiver with high priority that listens for the following intent:
```
<intent-filter>
        <action android:name="com.appboy.unity.AppboySample.intent.APPBOY_PUSH_RECEIVED" />
 </intent-filter>
```

Inside your Broadcast receiver, you can track incoming intents like so https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-unity/src/main/java/com/appboy/unity/AppboyUnityPushBroadcastReceiver.java#L16

**Comment by IgorGalimski** [comment]
Hi @Bucimis 
Thanks for the reply! But as I understand I can't use unity calls?

**Comment by Bucimis** [comment]
@IgorGalimski what use case within Unity do you want to accomplish while the app is in the bg? https://developer.android.com/guide/components/broadcasts has some options (`goAsync()` or `Jobscheduler`) for performing long-running work from a BroadcastReceiver.

**Comment by IgorGalimski** [comment]
I'd like to know when my game was opened by remote notification. How can I store information about it with Unity api, or mb android api when i receive a message from broadcast receiver?

**Comment by Bucimis** [comment]
@IgorGalimski if you create a broadcast receiver to open push opened intents from Braze, you'll need to handle parsing and sending that data into the Unity layer yourself. In your original post, you noted that 

> Callbacks on gameobject work when the game is online, I need to track it offline.

Our callback is called from a static broadcast receiver (defined in the Android Manifest), which means it should work when the app process is alive or when its killed. Can you elaborate more by what you mean by the game being offline vs online?

**Comment by IgorGalimski** [comment]
@Bucimis 
I meant when a game was unloaded from the memory. In this case, the broadcast receiver can receive a message, but I can't figure out a way how to send the message the Unity api. Or any other way to detect that game was opened by remote push, when the game was unloaded

**Comment by Bucimis** [comment]
@IgorGalimski I see, so you want to basically know whether the push opened the app or it was already open. If disable Braze's automatic deep link handling (see https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/integration/#enabling-automatic-deep-link-opening) and listen for the `APPBOY_NOTIFICATION_OPENED_SUFFIX`, you can then check whether you app is already open and take appropriate action, such as launching `AppboyUnityPlayerActivity` or opening the deep link.

Let me know if that's useful

**Comment by IgorGalimski** [comment]
Hi, @Bucimis !
I made a solution
`package com.test;

import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.util.Log;

import com.appboy.unity.AppboyUnityPushBroadcastReceiver;

public class TestAppboyUnityPushBroadcastReceiver extends AppboyUnityPushBroadcastReceiver 
{
    @Override
    public void onReceive(Context context, Intent intent) 
    {
        super.onReceive(context, intent);

        try 
        {
            String action = intent.getAction();

            SharedPreferences sharedpreferences = context.getSharedPreferences(BKAppboyUnityPlayerActivity.PREFERENCES_NAME, Context.MODE_PRIVATE);
            SharedPreferences.Editor editor = sharedpreferences.edit();

            editor.putString(BKAppboyUnityPlayerActivity.ACTION_KEY, action);
            editor.apply();
        }
        catch (Exception exception)
        {
            Log.i(TestAppboyUnityPlayerActivity.LOG_TAG, "OnCreate error: " + exception.getMessage());
        }
    }
}`


`package com.test;

import android.content.Context;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.util.Log;

import com.appboy.unity.AppboyUnityPlayerActivity;

public class TestAppboyUnityPlayerActivity extends AppboyUnityPlayerActivity 
{
    private static final String APPBOY_OPENED_ACTION = "APPBOY_NOTIFICATION_OPENED";
    
    public static final String PREFERENCES_NAME = "PREFERENCES";
    public static final String ACTION_KEY = "APPBOY_OPENED_ACTION";
    public static final String LOG_TAG = "Test";
    
    private static SharedPreferences _sharedPreferences;
    private static SharedPreferences.Editor _editor;

    @Override
    protected void onCreate(Bundle savedInstanceState) 
    {
        super.onCreate(savedInstanceState);
        
        try 
        {
            _sharedPreferences = this.getSharedPreferences(PREFERENCES_NAME, Context.MODE_PRIVATE);
            _editor = _sharedPreferences.edit();
        }
        catch (Exception exception)
        {
            Log.i(LOG_TAG, "OnCreate error: " + exception.getMessage());
        }
    }
    
    public static boolean IsOpenedByRemotePush()
    {
        try
        {
            return _sharedPreferences.getString(ACTION_KEY, "").contains(APPBOY_OPENED_ACTION);
        }
        catch (Exception exception)
        {
            Log.i(LOG_TAG, "IsOpenedByRemotePush error: " + exception.getMessage());
        }
        
        return false;
    }
    
    public static void ClearOpenedState()
    {
        try
        {
            _editor.remove(ACTION_KEY);
            _editor.apply();
        }
        catch (Exception exception)
        {
            Log.i(LOG_TAG, "ClearOpenedState error: " + exception.getMessage());
        }
    }
}`


It works. Could you please add this functionality (or more nice solution) in the package? I supose it'll useful for many people - know when a game was opened from remote push.

**Comment by IgorGalimski** [comment]
Up, please check out my solution
