### ISSUE TITLE
iOS push opened callback

### ISSUE THREAD

**Issue by IgorGalimski** [Appboy/appboy-unity-sdk#60]
Hi! I use appboy 1.2.1 version and I have a problem - iOSPushOpenedCallbackMethod doesn't call after opening a game from the background. My GO - doesn't DestroyOnLoad, it's named in config. How doesn't the method iOSPushOpenedCallbackMethodName work?

**Comment by radixdev** [comment]
Hello @IgorGalimski ,

Apologies for the late response. We're investigating this callback and should get back to you shortly.

**Comment by IgorGalimski** [comment]
Hi @radixdev 
Good, that was nothing to be sorry ;)

**Comment by radixdev** [comment]
Hi @IgorGalimski ,

It looks like the ios 10 methods weren't forwarding from the `userNotificationCenter`. That will be fixed in the newest release.

**Comment by radixdev** [comment]
This was addressed and tested in the latest release, 2.3.0. Please let us know if this fixes your issue

**Comment by IgorGalimski** [comment]
Hi! Many thanks! I'll share the result!
