### ISSUE TITLE
Set Push Listener unused

### ISSUE THREAD

**Issue by kolibrigames-ajimine-vahid** [Appboy/appboy-unity-sdk#61]
https://github.com/Appboy/appboy-unity-sdk/blob/9e6557a050f78b507169619030db447b76eb4801/Assets/Plugins/Appboy/Editor/PostBuild.cs#L24

Is this supposed to be here? Currently this const is not used. What is this for? Is this used for `Direct Opens`?

![image](https://user-images.githubusercontent.com/64904295/86780291-e33a6280-c05c-11ea-99f9-37cc6e262d38.png)

**Comment by Bucimis** [comment]
@kolibrigames-ajimine-vahid thanks for reporting! That constant appears to be dead code which we'll address in a coming release. What use case are you trying to accomplish?

**Comment by radixdev** [comment]
That field removed in the latest release.
