### ISSUE TITLE
Missing notification icons on Android (v.2.1.1)

### ISSUE THREAD

**Issue by luke-boniface** [Appboy/appboy-unity-sdk#62]
### Problem:
Push campaign notifications delivered to Android devices are missing their icons despite being correctly configured in the AppBoyConfig asset.

The problem is the `appboy-generated.xml` does not use the correct export settings for the icons (using `string` instead of `drawable`).

### Suggestion:
The [following lines](https://github.com/Appboy/appboy-unity-sdk/blob/master/Assets/Plugins/Appboy/Editor/PreBuild.cs#L60-L61) should use `drawable` as per the [Braze documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/unity/android/push_notifications/#step-3-configure-your-appboyxml)

### Additional info
- Unity 2018.4.19f1
- Braze v.2.1.1

**Comment by radixdev** [comment]
You're 100% correct. You can expect a fix very shortly

**Comment by radixdev** [comment]
Hi @luke-boniface ,

Sorry for the delay. This was fixed in the latest Unity release as of 6 days ago.

**Comment by luke-boniface** [comment]
Yep, confirmed fixed - thanks for the quick turnaround!
