### ISSUE TITLE
Appsflyer intergration issue

### ISSUE THREAD

**Issue by IgorGalimski** [Appboy/appboy-unity-sdk#63]
Hi!
My team is having a trouble with Appsflyer and Appboy. We receive a crash
1 case
* An app was open by invite link
* The apps in the background
* The app was open by icon

2 case
* The app was opened by icon
* The apps in the background
* The app was open by invite link

I receive the crash only when I use AppboyActivity. It's required by the documentation. With UnityPlayerActivity everything works well. The crash is not readable.
Please, check the integration with Appsflyer.

Link - https://boardkings.onelink.me/Fymc/50cd9536

Appsflyer 5.4.2
Appboy 2.4.0

https://drive.google.com/file/d/1m40Gu97TndFeM8lGvjScTz1aOSDRTSFl/view?usp=sharing
https://drive.google.com/file/d/1PR65SiDke_YIw-Jtp6RD0uhYBC1tbDrX/view?usp=sharing

**Comment by radixdev** [comment]
Hi @IgorGalimski ,

Which OS are you experiencing this crash on?

**Comment by IgorGalimski** [comment]
SGS 9+, Android 8.0.0, Samsung Experience version 9.0

**Comment by radixdev** [comment]
Can you provide a stacktrace or tombstone of the crash?

**Comment by IgorGalimski** [comment]
<img width="1229" alt="Screen Shot 2020-08-18 at 20 29 19" src="https://user-images.githubusercontent.com/19680568/90553578-4b707e00-e19d-11ea-811b-ca2abebd46de.png">

**Comment by radixdev** [comment]
There doesn't appear to be anything Braze related in that screenshot so I'm not sure how to proceed. Can you route this through `support@braze.com`? 

Thanks,
Julian

**Comment by IgorGalimski** [comment]
Maybe it's Appsflyer's issue. I wrote, please, check the email

**Comment by IndiumCrypto** [comment]
Cool to see developers of boardkings here!
