### ISSUE TITLE
Firebase activity

### ISSUE THREAD

**Issue by IgorGalimski** [Appboy/appboy-unity-sdk#64]
Hi! In my project as main activity I use AppboyUnityPlayerActivity. Should I extend it from firebase activity according to this?
https://firebase.google.com/docs/cloud-messaging/unity/client#android
<img width="974" alt="Screen Shot 2020-08-19 at 18 18 50" src="https://user-images.githubusercontent.com/19680568/90653914-749a1880-e248-11ea-9097-e0a73e1675bb.png">

**Comment by Bucimis** [comment]
@IgorGalimski you can subclass either Firebase's custom UnityPlayerActivity or our UnityPlayerActivity, but not both.  If you use ours, you should follow Firebase's "Configuring a custom entry point Activity" docs to manually add Firebase functionality. If you use Firebase's, you will need to extend your subclass's behavior with Braze functionality by porting the following implementation manually into your activity: https://github.com/Appboy/appboy-android-sdk/blob/e67e09f785adeff075a5d7710e79f41ed3676a6a/android-sdk-unity/src/main/java/com/appboy/unity/AppboyUnityPlayerActivity.java#L17

**Comment by IgorGalimski** [comment]
Can I extent AppboyUnityPlayerActivity from MessagingUnityPlayerActivity?

**Comment by radixdev** [comment]
Hi @IgorGalimski ,

That composition would likely work. The overrides in `AppboyUnityPlayerActivity` are just for session/in-app message management and would happily co-exist in any standard Activity.
