### ISSUE TITLE
Notification Center tracker 

### ISSUE THREAD

**Issue by IgorGalimski** [Appboy/appboy-unity-sdk#66]
Hi! I started to use userNotificationCenter
https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623117-application?language=objc
And stopped to received callback here
<img width="1409" alt="Screen Shot 2020-09-04 at 17 50 48" src="https://user-images.githubusercontent.com/19680568/92252659-369f2480-eed7-11ea-87a7-0c5ca33d4baa.png">

Could you please check - can I use new callback? It calls with local and remote pushes. Will everything be ok?
Thanks!

**Comment by Bucimis** [comment]
Hi @IgorGalimski - the callback should work fine and our delegates will only do anything if the push is from Braze. That said, I would recommend testing all relevant use cases to be sure behavior is as expected.

**Comment by IgorGalimski** [comment]
Hi! I'd like to use new UNUserNotificationCenter to local notification, and these callbacks don't work
https://stackoverflow.com/questions/39300865/didreceivelocalnotification-not-getting-called-after-using-unusernotificationcen

Could you please check it?

**Comment by Bucimis** [comment]
@IgorGalimski a few more questions

1) Which version of the Braze Unity SDK are you using?
2) Is your desired end state:
  a) Use UNUserNotificationCenter delegates only
  b) Use UNUserNotificationCenter delegates *and* pre-iOS 10 delegates

**Comment by IgorGalimski** [comment]
Hi, @Bucimis !
1. Appboy iOS native SDK 3.21.3
2. a) because I can't use pre-IOS 10 delegates with new UNUserNotificationCenter
Thanks!

**Comment by Bucimis** [comment]
@IgorGalimski gotcha, I see. Thanks for the context. If you haven't yet, you likely need to upgrade to Unity SDK 2.1.0 (which also uses iOS native SDK 3.21.3) https://github.com/Appboy/appboy-unity-sdk/blob/master/CHANGELOG.md#210 since as you noticed, the UserNotifications framework doesn't coexist well with existing delegates.

**Comment by IgorGalimski** [comment]
Hi, @Bucimis ! I checked - we already use this version. Shouldn't I worry about the delegates? They don't work and don't send callbacks further.

**Comment by Bucimis** [comment]
@IgorGalimski does it work with remote notifications only, or does it not work in either case?

**Comment by IgorGalimski** [comment]
Old callbacks for remote notifications don't work

**Comment by Bucimis** [comment]
@IgorGalimski that is expected. If you implement `application:didReceiveRemoteNotification:fetchCompletionHandler` and `userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler` for iOS 10 notifications, in most cases only the `UserNotificationFramework` delegate will get called, not both of them.

**Comment by IgorGalimski** [comment]
Hi, @Bucimis ! Thanks! Could you please check - what I need to do to fix it? Should I just move 
`  [[AppboyUnityManager sharedInstance] registerApplication:application
                              didReceiveRemoteNotification:userInfo
                              fetchCompletionHandler:nil];`

to UserNotificationFramework callbacks?

Thanks!

**Comment by Bucimis** [comment]
@IgorGalimski yep, note that the UserNotificationFramework callbacks live in `AppboyUnityManager`, e.g. https://github.com/Appboy/appboy-unity-sdk/blob/master/Assets/Plugins/iOS/AppboyUnityManager.mm#L321

**Comment by IgorGalimski** [comment]
Hi, @Bucimis !
Does it mean I shouldn't worry about the old callbacks?

**Comment by Bucimis** [comment]
@IgorGalimski you only need to worry about the old callbacks for `silent` push. The new callbacks handle all non-`silent` cases, see https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app?language=objc (silent push) https://developer.apple.com/documentation/usernotifications/handling_notifications_and_notification-related_actions?language=objc (user actions)

**Comment by IgorGalimski** [comment]
Understood, thanks!
