### ISSUE TITLE
OnReceive and onPause crashes

### ISSUE THREAD

**Issue by IgorGalimski** [Appboy/appboy-unity-sdk#67]
Hi! In the google play developer console I see a lot of crashes when a push is received. Could you please advise - what can I do to get rid of it?
I use Appboy v 2.2.2
Thanks!
<img width="960" alt="Screen Shot 2020-09-09 at 16 34 41" src="https://user-images.githubusercontent.com/19680568/92607406-c3bdf100-f2bc-11ea-99c7-a7dfa0b62b81.png">
<img width="956" alt="Screen Shot 2020-09-09 at 16 34 48" src="https://user-images.githubusercontent.com/19680568/92607425-c91b3b80-f2bc-11ea-8a20-f89cf69affb2.png">
<img width="948" alt="Screen Shot 2020-09-09 at 16 34 55" src="https://user-images.githubusercontent.com/19680568/92607430-c9b3d200-f2bc-11ea-854e-56cf5850c86a.png">
<img width="1000" alt="Screen Shot 2020-09-09 at 16 35 44" src="https://user-images.githubusercontent.com/19680568/92607433-ca4c6880-f2bc-11ea-9853-ea4e47e84657.png">

**Comment by radixdev** [comment]
1. Is there a way to reproduce these crashes? 
2. Do you have more detailed stacktraces (like the very last image provided)?

These crashes appear to be devices running low on memory and not indicative of some issue in the SDK. In the last stacktrace, the OOM resulted from simply starting a thread and not some hugely memory intensive operation.

**Comment by IgorGalimski** [comment]
Hi!
1. No, I've not reproduced the crash
2. No, only from GooglePlayConsole and Appcenter

Yes, but I don't see other OutOfMemoryCrash, only with OnReceive and OnPause methods. Could you please provide a way - how safely clean the RAM memory before starting a new thread?

Thanks!

**Comment by kolibrigames-ajimine-vahid** [comment]
Ah, we encountered this error quite a bit. This is not an SDK issue, but a documentation integration issue. You need to set the `launchMode` in the `AndroidManifest` file to `"singleTask"`.

```
<activity android:name="com.appboy.unity.AppboyUnityPlayerActivity" 
      android:label="@string/app_name"
      android:launchMode="singleTask"
```

[Documentation on launchMode](https://developer.android.com/guide/topics/manifest/activity-element#lmode)

**Comment by IgorGalimski** [comment]
@radixdev 
Hi! Please, don't close it
I asked my team - my change launchMode to singleTop, because of issues with IronSource rewarded video. When we start to watch a new video it creates a new activity. If you leave an app at this moment and then enter again the activity with video is lost. But as I understand with singleTop we create a copy of current Unity activity every time when we receive a push. And it causes crashes, right?

Thanks!

**Comment by radixdev** [comment]
We have been tracking this issue internally and will be closing out this issue.
