### ISSUE TITLE
`AppboyConfig` Missing `AndroidDisplayInAppMessages` configuration setting

### ISSUE THREAD

**Issue by kolibrigames-ajimine-vahid** [Appboy/appboy-unity-sdk#68]
https://github.com/Appboy/appboy-unity-sdk/blob/40571203194e8fb3fa088d11246c7c5343b6543c/Assets/Plugins/Appboy/Editor/PreBuild.cs#L63

The `AppboyConfig` is missing the field `AppboyConfig.AndroidDisplayInAppMessages` or `AppboyConfig.AndroidInAppShowInAppMessagesAutomatically`

`cfg = AddBooleanKey(cfg, "com_appboy_inapp_show_inapp_messages_automatically", AppboyConfig.AndroidInAppShowInAppMessagesAutomatically);`

**Comment by kolibrigames-ajimine-vahid** [comment]
If needed, I can do a PR to fix this issue as we need this for our use case

**Comment by radixdev** [comment]
Hi @kolibrigames-ajimine-vahid ,

A PR would be appreciated using `AppboyConfig.AndroidInAppShowInAppMessagesAutomatically`. On the native android SDK side, it looks like that field isn't being used however. I'll file an issue to have it be used and should be in the next native android SDK release.

**Comment by kolibrigames-ajimine-vahid** [comment]
Before I do a PR, I will need to double check with my company's legal team

**Comment by radixdev** [comment]
Hi @kolibrigames-ajimine-vahid ,

Actually I will just include this in the next Unity SDK release myself. Thanks for your patience.

**Comment by radixdev** [comment]
This will be included in the next unity release, alongside an update to android 10.0.0 which makes this field usable

**Comment by radixdev** [comment]
Added in 2.6.0
