### ISSUE TITLE
androidSessionTimeoutSeconds should be an INT

### ISSUE THREAD

**Issue by kolibrigames-ajimine-vahid** [Appboy/appboy-unity-sdk#69]
https://github.com/Appboy/appboy-unity-sdk/blob/40571203194e8fb3fa088d11246c7c5343b6543c/Assets/Plugins/Appboy/Editor/AppboyConfig.cs#L46

There is no real reason why this shouldn't be a string

**Comment by radixdev** [comment]
Hi @kolibrigames-ajimine-vahid ,

This is treated as a string since the unity editor accepts strings. In https://github.com/Appboy/appboy-unity-sdk/blob/cbea9db679123459a96a5e85310aac46f563ed67/Assets/Plugins/Appboy/Editor/PreBuild.cs#L74 , that value is treated as an integer when applied.

**Comment by kolibrigames-ajimine-vahid** [comment]
https://github.com/Appboy/appboy-unity-sdk/blob/40571203194e8fb3fa088d11246c7c5343b6543c/Assets/Plugins/Appboy/Editor/AppboyConfig.cs#L46

No. This should not be a string.

https://github.com/Appboy/appboy-unity-sdk/blob/cbea9db679123459a96a5e85310aac46f563ed67/Assets/Plugins/Appboy/Editor/PreBuild.cs#L130

You literally have a method that converts a string to an it which is not necessary and only add additional complexity since you already have this:

https://github.com/Appboy/appboy-unity-sdk/blob/cbea9db679123459a96a5e85310aac46f563ed67/Assets/Plugins/Appboy/Editor/PreBuild.cs#L122

Also, the Editor `ScriptableObjects` can take `int` values.

**Comment by radixdev** [comment]
Hi @kolibrigames-ajimine-vahid ,

I closed this prematurely, apologies. I'll add a story to our backlog to move this over to an integer. It will require migration work (since existing config blobs will store the value as a string) so I can't guarantee when it will be completed.

Julian
