### ISSUE TITLE
Silent Push Notifications Crashes App for iOS 14 devices

### ISSUE THREAD

**Issue by kolibrigames-ajimine-vahid** [Appboy/appboy-unity-sdk#71]
https://github.com/Appboy/appboy-unity-sdk/blob/40571203194e8fb3fa088d11246c7c5343b6543c/Assets/Plugins/iOS/AppboyUnityManager.mm#L312

After testing, it looks like this call crashes the app upon receiving a silent push notification. This only occurs on iOS 14, but works fine on iOS 12 and 13.

**Comment by Bucimis** [comment]
Closing in favor of https://github.com/Appboy/appboy-ios-sdk/issues/256 since the Braze Unity SDK delegate simply wraps the Braze iOS SDK delegate
