### ISSUE TITLE
AAR files not set to run on Android platform

### ISSUE THREAD

**Issue by kolibrigames-ajimine-vahid** [Appboy/appboy-unity-sdk#73]
https://github.com/Appboy/appboy-unity-sdk/blob/6f5e3484b7a39178252a9ae5d09f468ed0f4da0c/Assets/Plugins/Android/appboy-ui.aar.meta#L19

https://github.com/Appboy/appboy-unity-sdk/blob/6f5e3484b7a39178252a9ae5d09f468ed0f4da0c/Assets/Plugins/Android/appboy-unity.aar.meta#L19

https://github.com/Appboy/appboy-unity-sdk/blob/6f5e3484b7a39178252a9ae5d09f468ed0f4da0c/Assets/Plugins/Android/appboy.aar.meta#L19

All the android files are excluded from Android builds and need to be fixed.

-----

Here is how to solve the issue:

![image](https://user-images.githubusercontent.com/64904295/95199487-2da6b900-07dd-11eb-8266-2aa986b07895.png)

**Comment by Bucimis** [comment]
@kolibrigames-ajimine-vahid thanks for raising! 

Let us know if the following fix works for you and we'll release a fix asap:

https://github.com/Appboy/appboy-unity-sdk/pull/74
