### ISSUE TITLE
Using rich notification in Unity

### ISSUE THREAD

**Issue by IgorGalimski** [Appboy/appboy-unity-sdk#75]
Hi!
I have a problem - I need to add supporting reach notifications. I've tried to use it https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/rich/
but it didn't work in Unity. When I add files from the example manually I don't see info.plist in Xcode project. Maybe you have an example how to use it?

I tried this
https://answers.unity.com/questions/1407184/create-notification-service-extension-from-post-bu.html
but it didn't work ;(

Thanks!

**Comment by radixdev** [comment]
Can you route this through support@braze.com instead of a Github issue? This appears to be integration related and not a bug anywhere.

**Comment by IgorGalimski** [comment]
Hi! Yes, sure. Please, remove the thread.
Thanks!
