### ISSUE TITLE
Crash with Content-Available flag

### ISSUE THREAD

**Issue by IgorGalimski** [Appboy/appboy-unity-sdk#76]
Hi! I receive a crash when I put content-available flag in a game, when I didn't implement rich pushes. Could you please check?

Appboy 2.2.2
Xcode 11.6
Unity 2018.4.25f1
iOS 14.0
<img width="581" alt="Screen Shot 2020-10-20 at 15 47 00" src="https://user-images.githubusercontent.com/19680568/96588077-d54add80-12eb-11eb-81bd-b96bcda8875d.png">

<img width="1245" alt="Screen Shot 2020-10-20 at 15 46 52" src="https://user-images.githubusercontent.com/19680568/96588061-d1b75680-12eb-11eb-8d5b-08bb533f44fd.png">

**Comment by Bucimis** [comment]
@IgorGalimski this crash is a known issue on iOS 14 that occurs when the `completionHandler` in `application:didReceiveRemoteNotification:fetchCompletionHandler:` (https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application?language=objc) gets called more than once. Appboy's delegate methods *do* call completionHandlers, so there are two ways to address this:
1) Don't pass completionHandlers to Appboy's delegate methods (pass `nil` instead) and call them yourself.
2) Don't call completionHandler in your own code, and pass the completionHandler to Appboy's delegate methods.

**Comment by IgorGalimski** [comment]
Hi! Thanks for the reply!
