### ISSUE TITLE
Question about appboy.xml

### ISSUE THREAD

**Issue by MartinGonzalez** [Appboy/appboy-unity-sdk#77]
HI there
I've seen that when building Unity an appboy-generated.xml is created. But also there is an appboy.xml in Plugins/Android/res/values. 

Which one is being used?
Should we delete appboy.xml?
Should both exist?

Thanks

**Comment by Bucimis** [comment]
@MartinGonzalez If you need to split your configuration across both, technically you can have both as long as they don't duplicate configuration values. See https://github.com/Appboy/appboy-unity-sdk/blob/c83abd353737b9ac9d9014a496354954fcfd3187/CHANGELOG.md#added-4 for more details on when and how appboy-generated.xml is created

**Comment by MartinGonzalez** [comment]
But the Braze tool works with the generated.xml one?
I don't know why to have both or if it's safe to delete appboy.xml

**Comment by Bucimis** [comment]
@MartinGonzalez its safe to delete appboy.xml if you aren't configuring anything in that file

**Comment by MartinGonzalez** [comment]
Thanks!
