### ISSUE TITLE
'PBXProject.GetUnityTargetName()' is obsolete: 'This function is deprecated

### ISSUE THREAD

**Issue by idamaeng** [Appboy/appboy-unity-sdk#79]
Unity Version: 2019.4.10f1
Braze SDK Version: 2.7.0

I am not able to compile my project after installing the latest Braze SDK Version, because it is using deprecated functions.

Error Message:
Assets/Plugins/Appboy/Editor/PostBuild.cs(57,36): error CS0619: 'PBXProject.GetUnityTargetName()' is obsolete: 'This function is deprecated. There are two targets now, call GetUnityMainTargetGuid() - for app or GetUnityFrameworkTargetGuid() - for source/plugins to get Guid instead of calling to TargetGuidByName(GetUnityTargetName()).'

**Comment by Bucimis** [comment]
@idamaeng thanks for reporting and we'll look to get this fixed and released. In the meantime would you be able to customize your local `PostBuild.cs` to use `GetUnityMainTargetGuid()`?

**Comment by idamaeng** [comment]
> @idamaeng thanks for reporting and we'll look to get this fixed and released. In the meantime would you be able to customize your local `PostBuild.cs` to use `GetUnityMainTargetGuid()`?

Added your suggestion to PostBuild.cs and it works. Looking forward to download your updated Unity package :).

**Comment by radixdev** [comment]
Fixed in release 2.7.1, released just now.
