### ISSUE TITLE
None of the selected users have matching push tokens for iOS Push

### ISSUE THREAD

**Issue by idamaeng** [Appboy/appboy-unity-sdk#80]
Unity Version: 2019.4.10f1
Braze SDK Version: 2.7.0
iOS Version: 13.7

I am trying to get Braze Push Notifications running on my iOS Device. I have successfully installed the SDK and I am able to create a user + custom attributes. But as soon as I am trying to send a test notification to my phone using the user id associated with it, following message pops up:

**Warning: None of the selected users have matching push tokens for iOS Push.** 

In the Unity settings for Braze "Disable Auto Push Registration" is set to false.

Any ideas what I am doing wrong to get Push Notifications up and running?

**Comment by Bucimis** [comment]
Hi @idamaeng, a few thoughts:

1. If you disable auto push registration, you should follow our native iOS integration to get set up with https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/integration/ (high level, this will involve setting your unnotification delegate, adding the push capability to XCode, requesting push perms from the user, passing push token to braze, and implementing delegates to handle incoming notification data)
2. If you implement push successfully, you should see a `push_token` be sent up in requests from the SDK to the Braze backend. 

If you still have trouble after following our native push docs, please reach out to support@braze.com for help getting set up with push.
