### ISSUE TITLE
ios OPT-In Popup

### ISSUE THREAD

**Issue by idamaeng** [Appboy/appboy-unity-sdk#82]
Unity Version: 2019.4.10f1
Braze SDK Version: 2.8.0
iOS: 13.7

Hi, I am trying to get braze running on iOS. I followed your documentation steps for auto. integration of the plugin.
This results in a user which is Provisionally Authorized to receive push notifications. How can I get rid of the provisionally state? If I start the app for the first time I am expecting an opt-in popup to appear, but it does not. What steps are needed to make the popup appear on first app start? 

Please help me I am close to tears, because testing this really sucks :)

**Comment by Bucimis** [comment]
@idamaeng thanks for reaching out + sorry to hear it's been stressful!

Yes, that is correct that as of now, using automatic push integration will always result in a user being provisionally authorized. We are going to release an update in the next few days that will allow integrators to specify provisional vs pop-up and control the timing of the prompt.

Does that work for your timing?

**Comment by idamaeng** [comment]
Thanks for that info. It would have been nice if you mention that fact in your documentation.
Looking forward to that update.

**Comment by Bucimis** [comment]
Thanks for the feedback, I've submitted a fix to our documentation to reflect the current state of the world.

**Comment by idamaeng** [comment]
Hi, is there any estimate of the release date of the new version?

**Comment by Bucimis** [comment]
Hi @idamaeng, we're still waiting on some customer feedback before we release. Would you be interested in trying a pre-release unitypackage with instructions on how to get set up?

**Comment by Bucimis** [comment]
Hi @idamaeng just following up here on ^

**Comment by idamaeng** [comment]
Thank you for offering me the pre release. But unfortunately I am not able to test pre release versions of plugins with our current project. I am really looking forward to that new release - hopefully in the next couple of days ;)

**Comment by Bucimis** [comment]
@idamaeng thanks for your patience - we just released 3.0.0 which provides the ability to toggle provisional auth on or off from the Braze configuration editor. You can also turn off automatic registration and request registration from the Unity layer using `AppboyBinding.PromptUserForPushPermissions(bool provisional)`. 🍻
