### ISSUE TITLE
How to get android FCM token from c# layer? - is there a helper . couldnt find in any docs!

### ISSUE THREAD

**Issue by shanukp** [Appboy/appboy-unity-sdk#87]

**Comment by Bucimis** [comment]
@shanukp Hi Shanu,

You should retrieve your token from Firebase directly (See https://firebase.google.com/docs/cloud-messaging/unity/client#initialize for how to set up a token listener). There is currently no way to get the push token from the Braze SDK

**Comment by shanukp** [comment]
For this to work should I disable auto registration of device in  braze
setting ?

Also do I need to remove changes suggested by braze for Android manifest
and keep one's suggested by Firebase - is this needed or changes suggested
alone by braze works with below piece of code

public void Start() {
  Firebase.Messaging.FirebaseMessaging.TokenReceived += OnTokenReceived;
  Firebase.Messaging.FirebaseMessaging.MessageReceived += OnMessageReceived;
}

public void OnTokenReceived(object sender,
Firebase.Messaging.TokenReceivedEventArgs token) {
  UnityEngine.Debug.Log("Received Registration Token: " + token.Token);
}

public void OnMessageReceived(object sender,
Firebase.Messaging.MessageReceivedEventArgs e) {
  UnityEngine.Debug.Log("Received a new message from: " + e.Message.From);
}


Also do i have to manually update tokens to braze after this?

**Comment by radixdev** [comment]
Hi @shanukp ,

You can also do 

```
#if UNITY_ANDROID
  BrazeAndroidPlatform binding = (BrazeAndroidPlatform) Appboy.AppboyBinding.mBinding;
  return binding.Appboy.Call<string>("getAppboyPushMessageRegistrationId");
#endif
```

This gets the singleton on the binding and allows you to call methods on it directly. Let us know if this works for you.

**Comment by shanukp** [comment]
Yes it worked . this works every android version and scenario  right .. any gotcha's?

**Comment by radixdev** [comment]
Yes to both. As long as the Android SDK has the token, it will return it via that method. Only gotcha is that that method will be deprecated and removed (not for a very very long time however) in favor of `getRegisteredPushToken()` but unity hasn't been updated to have it yet. There's nothing else to worry about!

**Comment by shanukp** [comment]
Thanks!
