### ISSUE TITLE
Output Message

### ISSUE THREAD

**Issue by NikanGameDev** [Appboy/appboy-unity-sdk#88]
My output says: Assets\PurchaseButton.cs(7,7): error CS0246: The type or namespace name 'Utilities' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Bucimis** [comment]
@NikanGameDev Thanks for getting in touch. I don't think the Braze SDK includes a file called `PurchaseButton.cs`. Could you point to the file in https://github.com/Appboy/appboy-unity-sdk/tree/master/Assets/Plugins/Appboy causing you difficulties?

**Comment by radixdev** [comment]
Hey @NikanGameDev ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
