### ISSUE TITLE
Unity - Android: Multiple Braze InApp Popups displayed overlayed and buttons not responsive

### ISSUE THREAD

**Issue by pletoss** [Appboy/appboy-unity-sdk#92]
We're currently working on integrating Braze In-Apps in our Unity Game using the Unity Braze SDK.

When displaying a second in-app popup in the same session, it gets overlayed on top of the previous one each time, and the buttons are not responsive anymore.  

More detail: If we trigger one specific In-App Message A by one triggerA and then another In-App Message B by triggerB it starts to overlay both In-App Popups on top of eachother, and buttons are not responsive anymore. It can only be closed with the android back button, but afterwards B overlaid on top of A will both be re-show each time triggerB is retriggered. 

I've attached a screenshot. 

On iOS this has no issues and behaves normally.

![Screenshot_2022-03-23-12-08-30-60_33eb6a45a6d287c3e0e51f3f9abe4f86](https://user-images.githubusercontent.com/636215/159717468-a693fbce-1124-4c34-83bb-380c1f0ef481.jpg)

Any help/pointers is appreciated.

**Comment by pletoss** [comment]
More info: these are both custom HTML in-apps.

**Comment by radixdev** [comment]
Hi @pletoss ,

1. Can you provide more details on your in-app customization/integration?
2. Can you provide verbose logs (set "AndroidLogLevel" in your Braze Unity config to `0`) of a reproduction of the issue, starting from a fresh app start?
3. Can you provide your SDK version and device this was tested on?

**Comment by pletoss** [comment]
Hey @radixdev thanks for looking into this. However in the meantime I've reached out to your support email, and Jen is looking into this. He should have all that info + some more sensitive one that can't be public here.

**Comment by radixdev** [comment]
Hi @pletoss ,

I'm closing this issue for now. Please let me us if you continue to have issues and we'll debug further on the support email front.
