### ISSUE TITLE
[Feature]:  changelog or versioning doc should be inside plugin folder

### ISSUE THREAD

**Issue by Ale1** [Appboy/appboy-unity-sdk#96]
### What problem are you facing?

If I open a unity project that is already using braze plugin, I have no easy way of knowing which version is installed. The repo as a whole has a changelog at the root of the project, but the installation instructions only require a sub-folder to be copied into the project.  The result is that the changelog is lost. 

### Workarounds

making a copy of the changelog.md and pasting it inside the plugin folder. 

### Ideal Solution

UPM package with proper versioning and documentation.

**Comment by radixdev** [comment]
Hello @Ale1 ,

We've filed this story internally and will provide any updates here. Thanks for filing!
